### ISSUE TITLE
Fix lobby settings being overriden

### ISSUE THREAD

**Issue by Prefix** [Softsplit/sandbox-plus-plus#104]
**Is your feature request related to a problem? Please describe.**
https://github.com/Softsplit/sandbox/blob/96cd84de148676fb82482abbd1fa777478534fa5/Code/Components/MapPlayerSpawner.cs#L12
hardcoded Name = "Sandbox Classic Server"

**Describe the solution you'd like**
Would love to be able to set lobby name. If dedicated server - hostname

**Describe alternatives you've considered**
Take hostname cvar if exists

**Additional context**

**Comment by Asphaltian** [comment]
No.

**Comment by Asphaltian** [comment]
Fixed

**Comment by Asphaltian** [comment]
Reverted (oopsies!)

**Comment by Asphaltian** [comment]
Re-reverted
