### ISSUE TITLE
incorrect data

### ISSUE THREAD

**Issue by Gudhein3** [Softsplit/sandbox-plus-plus#36]
RU localization is made by boxden [Commit](https://github.com/Softsplit/sandbox-classic/commit/e4285a6e0481016f74161e176f7cee9a1ad51e0a)

**Comment by Gudhein3** [comment]
[Fix](https://github.com/Softsplit/sandbox-classic/commit/d8b5a729cf36b0859cea75715d6142c001a5566a)

**Comment by Asphaltian** [comment]
They didn't even respond yet...
