### ISSUE TITLE
Can't start a server

### ISSUE THREAD

**Issue by aaronisda** [Softsplit/sandbox-plus-plus#55]
Whenever I try and make a server, it's just pink! I can't select anything or do anything. I have no idea if this is an issue on my end or your guys end.
![20240725224602_1](https://github.com/user-attachments/assets/c2a3aa09-0c18-4288-973c-0b7d5597df4f)
Here is an example of the issue.

**Comment by Asphaltian** [comment]
This isn't caused by us and is Facepunch's responsibility to fix, see facepunch/sbox-issues#5930
