### ISSUE TITLE
Reimplement remaining tools

### ISSUE THREAD

**Issue by Asphaltian** [Softsplit/sandbox-plus-plus#97]
### List of tools to reimplement

- [x] Balloon
- [x] Box Shooter
- [x] Color
- [x] Lamp
- [x] Leaf Blower
- [x] Light
- [x] Model Skin Changer
- [x] No Collide 
- [x] Remover
- [x] Resizer
- [x] Rope
- [x] Thruster
- [x] Weld
- [x] Wheel

**Comment by TeeMeeFe** [comment]
Don't forget about Axis as well as face poser and inflator

**Comment by Asphaltian** [comment]
We're going off the old tool list, so I don't think we'll be adding those

**Comment by Asphaltian** [comment]
> We're going off the old tool list, so I don't think we'll be adding those

Sandbox++ will be adding the following tools from now on: https://github.com/Softsplit/sandbox-plus-plus/issues/4

**Comment by Asphaltian** [comment]
Done
